name: excel2csv

on: [push]

jobs:
  run:
    name: excel2csv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'contributions/pyqalloy-contribute/requirements.txt'

      - name: Install Dependencies
        run: |
          python -m pip install -r contributions/pyqalloy-contribute/requirements.txt

      - name: Run excel2csv
        run: |
          python contributions/pyqalloy-contribute/excel2csv.py .

      - name: Run csv2readme
        run: |
          python contributions/pyqalloy-contribute/csv2readme.py .

      - name: Comment on commit
        uses: actions/github-script@v6
        with:
          script: |
            const commitSha = context.sha;
            const repoName = context.repo.repo;
            const commentBody = `@rdamaral: New ULTERA contribution on ${repoName} (${commitSha})`;
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commitSha,
              body: commentBody
            });